export const districts = [
  "Abura/Asebu/Kwamankese",
  "Accra Metropolis",
  "Adaklu-Anyigbe",
  "Adansi North",
  "Adansi South",
  "Afigya-Sekyere",
  "Afra Plains",
  "Ahafo Ano North",
  "Ahafo Ano South",
  "Ahuapim North",
  "Ahuapim South",
  "Ahanta West",
  "Akuapim North",
  "Akuapim South",
  "Amansie Central",
  "Amansie East",
  "Amansie West",
  "Asante Akim North",
  "Asante Akim South",
  "Asikuma/Odoben/Brakwa",
  "Assin North",
  "Assin South",
  "Asuogyaman",
  "Asunafo North",
  "Asunafo South",
  "Asutifi",
  "Atebubu-Amantin",
  "Atiwa",
  "Atwima",
  "Atwima Mponua",
  "Awutu/Effutu/Senya",
  "Aowin/Suaman",
  "Bawku Municipal",
  "Bawku West",
  "Berekum",
  "Bia",
  "Bibiani/Anhwiaso/Bekwai",
  "Bolgatanga Municipal",
  "Bongo",
  "Bole",
  "Botsomtwe/Atwima/Kwanhuma",
  "Builsa",
  "Bunkpurugu-Yunyoo",
  "Birim North",
  "Birim South",
  "Cape Coast Municipal",
  "Central Gonja",
  "Dangme East",
  "Dangme West",
  "Dormaa",
  "East Akim",
  "East Gonja",
  "East Mamprusi",
  "Ejisu-Juaben",
  "Ejura/Sekyedumase",
  "Fanteakwa",
  "Ga East",
  "Ga West",
  "Garu-Tempane",
  "Gomoa enda/Edina/Eguafo/Abirem",
  "Gushiegu",
  "Ho Municipal",
  "Hohoe",
  "Jaman North",
  "Jaman South",
  "Jasikan",
  "Jirapa/Lambussie",
  "Jomoro",
  "Juabeso",
  "Kassena/Nankana",
  "Keta",
  "Ketu",
  "Kintampo North",
  "Kintampo South",
  "Kpando",
  "Krachi",
  "Krachi East",
  "Kumasi Metropolitan",
  "Kwabre",
  "Kwahu South",
  "Kwahu West",
  "Kwaebibirem",
  "Lawra",
  "Manya Krobo",
  "Mfantsiman",
  "Mpohor/Wassa East",
  "Nanumba North",
  "Nanumba South",
  "Nkoranza",
  "Nkwanta North",
  "Nzema East",
  "Obuasi Municipal",
  "Offinso",
  "Pru",
  "Savelugu/Nanton",
  "Sawla-Tuna-Kalba",
  "Sekyere East",
  "Sekyere West",
  "Sene",
  "Sefwi-Wiawso",
  "Shama Ahanta East Metropolitan",
  "Sissala East",
  "Sissala West",
  "South Dayi",
  "South Tongu",
  "Sunyani Municipal",
  "Suhum/Kraboa/Coaltar",
  "Tamale Municipal",
  "Tain",
  "Talensi-Nabdam",
  "Tano North",
  "Tano South",
  "Tema Municipal",
  "Techiman Municipal",
  "Tolon/Kumbungu",
  "Tongu",
  "Twifo/Heman/Lower Denkyira",
  "Upper Denkyira",
  "Wa East",
  "Wa Municipal",
  "Wa West",
  "Wasa Amenfi East",
  "Wasa Amenfi West",
  "Wassa East",
  "West Akim",
  "West Gonja",
  "West Mamprusi",
  "Wenchi",
  "Yendi",
  "Yilo Krobo",
  "Zabzugu/Tatale",
]; // Array of districts
export const regions = [
  "Ashanti",
  "Brong Ahafo",
  "Central",
  "Eastern",
  "Greater Accra",
  "Northern",
  "Upper East",
  "Upper West",
  "Volta",
  "Western",
  "Savannah",
  "Bono East",
  "Oti",
  "Ahafo",
  "Western North",
  "North East",
]; // Array of regions
export const churches = [
  "Orthodox Churches",
  "Catholic Church",
  "Protestant Churches",
  "Charismatic Churches",
  "Evangelical Churches",
  "African Independent Churches",
  "Other Churches",
]; // Array of churches
export const validNationalities = [
  "Ghana",
  "Nigeria",
  "Senegal",
  "Mali",
  "Togo",
  "Cote D'iVoire",
]; // Array of valid nationalities
